# Use the specific version of Node.js as the base image
FROM node:20.15.0 AS build

# Set the working directory inside the container
WORKDIR /client 
 
# We bring the project dependencies into the working directory 
COPY package.json .

# Install all the project dependencies listed in package.json file
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

RUN npm run build

FROM nginx 

COPY --from=build /client/build /usr/share/nginx/html
