# first of all we need to create a this docker-compose.yaml file
# to configure mutiple dockers and combine them(docker for frontend, backend, and docker for database) 
#in this projec at the same time.
services:
  client:
    build:
      context: ./client
      
    #   dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    # volumes:
    #   - /app/node_modules
    #   - ./client:/app