name: Publish Docker images with Docker Compose


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./client
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./api
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Deploy services
        run: |
          docker-compose down
          docker-compose pull
          docker-compose up -d
