name: Frontend CI/CD Pipeline

on:
  push:
    branches:
      - main
      - frontend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <your-acr-name>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push frontend image
        run: |
          docker build -t <your-acr-name>.azurecr.io/frontend:latest ./client
          docker push <your-acr-name>.azurecr.io/frontend:latest

      - name: Deploy frontend service
        run: |
          docker-compose down
          docker-compose pull <your-acr-name>.azurecr.io/frontend:latest
          docker-compose up -d